apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: production
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: U3RyMG5nUGFzc3dvcmQhMjAyNQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: production
type: Opaque
data:
  username: Z3Vlc3Q=
  password: Z3Vlc3RAYjExMjAyNQ==
